import React from "react";
import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";

const styles = StyleSheet.create({
  page: { padding: 30, fontFamily: "Helvetica", backgroundColor: "#ffffff" },
  header: { textAlign: "center", marginBottom: 20, borderBottomWidth: 2, borderBottomColor: "#1e293b", paddingBottom: 10 },
  schoolName: { fontSize: 18, fontWeight: "bold", textTransform: "uppercase", marginBottom: 4 },
  reportTitle: { fontSize: 14, fontWeight: "bold", color: "#334155" },
  dateText: { fontSize: 10, color: "#64748b", marginTop: 5 },
  
  classSection: { marginTop: 15, marginBottom: 15 },
  classTitle: { fontSize: 12, fontWeight: "bold", backgroundColor: "#f1f5f9", padding: 6, marginBottom: 8, borderRadius: 4 },
  
  table: { width: "100%", borderWidth: 1, borderColor: "#e2e8f0", borderBottomWidth: 0, borderRightWidth: 0 },
  tableHeaderRow: { flexDirection: "row", backgroundColor: "#f8fafc", borderBottomWidth: 1, borderColor: "#e2e8f0" },
  tableRow: { flexDirection: "row", borderBottomWidth: 1, borderColor: "#e2e8f0" },
  tableCell: { padding: 6, borderRightWidth: 1, borderColor: "#e2e8f0", justifyContent: "center" },
  cellTextBold: { fontSize: 10, fontWeight: "bold", color: "#0f172a" },
  cellText: { fontSize: 10, color: "#334155" },
  
  footer: { position: "absolute", bottom: 30, left: 30, right: 30, textAlign: "center", fontSize: 9, color: "#94a3b8", borderTopWidth: 1, borderTopColor: "#e2e8f0", paddingTop: 10 }
});

const TCell = ({ text, width, align = "left", bold = false }) => (
  <View style={[styles.tableCell, { width }]}>
    <Text style={[bold ? styles.cellTextBold : styles.cellText, { textAlign: align }]}>{text}</Text>
  </View>
);

export default function StudentClassListTemplate({ groupedStudents }) {
  const currentDate = new Date().toLocaleDateString('en-GB');

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.schoolName}>Western School and College</Text>
          <Text style={styles.reportTitle}>CLASS-WISE STUDENT LIST</Text>
          <Text style={styles.dateText}>Date Generated: {currentDate}</Text>
        </View>

        {Object.entries(groupedStudents).map(([className, students]) => (
          <View key={className} style={styles.classSection}>
            <Text style={styles.classTitle}>Class: {className} ({students.length} Students)</Text>
            <View style={styles.table}>
              <View style={styles.tableHeaderRow}>
                <TCell text="Student ID" width="25%" bold />
                <TCell text="Roll No." width="20%" align="center" bold />
                <TCell text="Student Name" width="55%" bold />
              </View>
              {students.map((student, idx) => (
                <View key={idx} style={styles.tableRow}>
                  <TCell text={student.studentId || "-"} width="25%" />
                  <TCell text={student.rollNumber || student.roll || "-"} width="20%" align="center" />
                  <TCell text={student.fullName || "-"} width="55%" />
                </View>
              ))}
            </View>
          </View>
        ))}

        <Text style={styles.footer} fixed>
          Generated by Western School & College System • Page <Text render={({ pageNumber, totalPages }) => `${pageNumber} / ${totalPages}`} />
        </Text>
      </Page>
    </Document>
  );
}